"""new fields in user model

Revision ID: c2f587324835
Revises: 8a82af6d909c
Create Date: 2020-05-30 12:54:55.778751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2f587324835'
down_revision = '8a82af6d909c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('city', sa.String(), nullable=True))
    op.add_column('user', sa.Column('coords', sa.String(), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'link')
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'coords')
    op.drop_column('user', 'city')
    op.drop_column('user', 'age')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
